version: '3.8'
services:
  backend:
    build: ./devops-backend
    environment:
      - MYSQL_HOST=mysql  
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=my_database
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - "8080:8080"
    networks:
      - backend  # Backend should only be on the backend network
    depends_on:
      mysql:
        condition: service_healthy
 
  frontend:
    build: ./devops-frontend
    ports:
      - "80:5174"
    depends_on:
      - backend
    networks:
      - frontend    
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: my_database
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - mysql_/var/lib/mysql
    networks:
      - backend # MySQL should only be on the backend network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmy-secret-pw"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s # Add a start period to allow MySQL time to initialize

volumes:
  mysql_
networks:
  frontend:
  backend:
